# Generated by Django 4.1.4 on 2022-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=255, null=True)),
                ('payment', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
