# Generated by Django 4.1.4 on 2022-12-16 06:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_alter_job_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
