# Generated by Django 4.1.4 on 2022-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_job_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='job',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=255),
        ),
    ]
