# Generated by Django 4.1.4 on 2022-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_remove_job_timestamp_job_day_job_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
